spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    first:
      url: jdbc:mysql://localhost:3306/security_db?useUnicode=true&characterEncoding=utf-8
      data-username: root
      data-password: root
    second:
      url: jdbc:mysql://localhost:3306/security_db?useUnicode=true&characterEncoding=utf-8
      data-username: root
      data-password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  jackson:
    serialization:
      indent_output: true

